//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA.Recipe.InterfacesAdapters.Data.Recipe
{
    using System.Data.Entity;

    public partial class RecipeContext : DbContext
    {
        public RecipeContext()
            : base("name=RecipeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    
        public virtual DbSet<Amount> Amount { get; set; }
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WatchLater> WatchLater { get; set; }
    }
}
